### ISSUE TITLE
I need to make some additional settings when packaging. My settings cannot be used. Please help me. Thank you.

### ISSUE THREAD

**Issue by a37836323** [The-Nicholas-R-Barrow-Company-LLC/PyMacApp#6]
(venv) lilinze@lilinzedeMac-mini winwinwin % sudo /Users/lilinze/Downloads/winwinwin/venv/bin/python /Users/lilinze/Downloads/winwinwin/qianming.py 
Password:
2023-11-18 21:31:55,329 pymacapp >>> appfactory.py @ 49 in .__init__(...) [DEBUG]: App(self._name='yunwuai') created
2023-11-18 21:31:55,329 pymacapp >>> validators.py @ 27 in .validate_app_name(...) [INFO]: validated: yunwuai
2023-11-18 21:31:55,329 pymacapp >>> pyinstaller.py @ 61 in .spec(...) [DEBUG]:  --name 'yunwuai'
2023-11-18 21:31:55,329 pymacapp >>> validators.py @ 59 in .validate_file(...) [WARNING]: invalid file: /Users/lilinze/Downloads/winwinwin/独立exe启动器1.spec
Traceback (most recent call last):
  File "/Users/lilinze/Downloads/winwinwin/qianming.py", line 27, in <module>
    app.config(main).build().sign(APP_HASH)
    ^^^^^^^^^^^^^^^^
  File "/Users/lilinze/Downloads/winwinwin/venv/lib/python3.11/site-packages/pymacapp/buildtools/app/appfactory.py", line 88, in config
    self._spec = spec(name=self._name,
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lilinze/Downloads/winwinwin/venv/lib/python3.11/site-packages/pymacapp/pyinstaller.py", line 65, in spec
    raise BuildException(f"unable to validate {main_script=}")
pymacapp.exceptions.BuildException: unable to validate main_script='/Users/lilinze/Downloads/winwinwin/独立exe启动器1.spec'

**Comment by ghost** [comment]
Hi @a37836323 
The `BuildException` you are seeing (`invalid file: /Users/lilinze/Downloads/winwinwin/独立exe启动器1.spec`) is because the file was not found, i.e. the pathname is incorrect. This would solely be because MacOS was unable to locate the file. Please confirm the filepath is correct. 

Try running this command in a terminal:
```bash
cat /Users/lilinze/Downloads/winwinwin/独立exe启动器1.spec
```

If you get an error here, then the filepath is definitely wrong; if the above works, then you may want to rename your `.spec` file to something extremely simple (such as `app.spec`) and try again. It could be a character limitation issue.
